# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
   - master
 paths:
   exclude:
   - azure-pipelines-wpf.yml
   - .github/workflows/main.yml
   - src/PresenceLight/*
   - README.md

pool:
  vmImage: 'windows-latest'

variables:
  - group: Sign Client Credentials

  

strategy:
    matrix:
      Channel_Windows_x64_x86:
        ChannelName: Windows_x64_x86
        RID: win-x64
      Channel_Windows_ARM:
        ChannelName: Windows_ARM
        RID: win-arm
      Channel_macOS:
        ChannelName: macOS
        RID: osx-x64
      Channel_Linux_ARM:
        ChannelName: Linux_ARM
        RID: linux-arm
      Channel_Linux_ARM64:
        ChannelName: Linux_ARM64
        RID: linux-x64
      Channel_Linux_Musl_x64:
        ChannelName: Linux_Musl_x64
        RID: linux-x64
      Channel_Linux_Musl_ARM_x64:
        ChannelName: Linux_Musl_ARM_x64
        RID: linux-musl-x64
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 5.0.x'
    inputs:
      version: 5.0.x
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install -g nbgv
    displayName: Install NBGV tool

  - script: nbgv cloud -c -a
    displayName: Set Build Version
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      workingDirectory: src/PresenceLight.Worker
      arguments: -r $(RID) -c Release /p:PublishSingleFile=true -o $(Build.ArtifactStagingDirectory)/$(GitBuildVersionSimple)_$(ChannelName)
      publishWebProjects: false

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . SignClient
    displayName: Install SignTool tool

  - task: AzureCLI@2
    displayName: Scale Up Sign Service
    inputs:
      azureSubscription: 'Isaac Levin MSDN (a07802f5-f8df-47d8-9b88-79ba55cfb396)'
      scriptType: ps
      scriptLocation: 'inlineScript'
      inlineScript: 'az appservice plan update --name levin-signserv-asp-2dnwx6q6jwiay --resource-group SignService --sku P1V2'


  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\Build\'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)\Build\ToSign'

  - pwsh: |
      .\SignClient "Sign" `
      --baseDirectory "$(Build.SourcesDirectory)" `
      --input "**/*.{exe,zip}" `
      --config "$(Build.SourcesDirectory)\Build\ToSign\appsettings.json" `
      --filelist "$(Build.SourcesDirectory)\Build\ToSign\filelist.txt" `
      --user "$(SignClientUser)" `
      --secret "$(SignClientSecret)" `
      --name "PresenceLight" `
      --description "PresenceLight" `
      --descriptionUrl "https://github.com/isaacrlevin/PresenceLight"
    displayName: Authenticode Sign artifacts
    

  - task: AzureCLI@2
    displayName: Scale Down Sign Service
    inputs:
      azureSubscription: 'Isaac Levin MSDN (a07802f5-f8df-47d8-9b88-79ba55cfb396)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az appservice plan update --name levin-signserv-asp-2dnwx6q6jwiay --resource-group SignService --sku S1'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: $(GitBuildVersionSimple)_$(ChannelName)
      targetPath: $(Build.ArtifactStagingDirectory)/$(GitBuildVersionSimple)_$(ChannelName)
