version: '3.4'

services:
  presencelight.worker:
    build:
      context: .
      dockerfile: ../PresenceLight.Worker/Dockerfile
    image: ${DOCKER_REGISTRY-}presencelightworker
    ports:
      - "443"
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=presencelight
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/presencelight.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
