on:
  workflow_call:

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:

  Deploy_Choco:
    name: Deploy WPF Chocolatey
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v2
        name: Download Standalone Signed App Artifacts
        with:
          name: Standalone_Signed
          path: .\StandaloneSigned

      - uses: actions/download-artifact@v3
        if: ${{ github.event_name == 'push' }}
        name: Download Signing Scripts Artifacts
        with:
          name: SigningScripts
          path: .\SigningScripts

      - name: Get Version from Artifact (Push)
        if: ${{ github.event_name == 'push' }}
        run: |
          $version = Get-Content .\SigningScripts\version.txt
        shell: powershell

      - name: Get Version from Input (Workflow Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          version = "${{ inputs.Version }}"
        shell: powershell

      - name: Populate Version Environment Variable
        run: |
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - uses: actions/download-artifact@v2
        name: Download Chocolatey Artifacts
        with:
          name: Chocolatey
          path: .\Chocolatey

      - name: Update Chocolatey Files
        run: |
          .\Build\scripts\hash-files.ps1 -Version "${{ env.VERSION }}"
        shell: powershell

      - name: Push to Chocolatey
        run: |
          .\Build\scripts\push-choco.ps1 -Version "${{ env.VERSION}}" -CHOCOAPIKEY "${{ secrets.CHOCOAPIKEY}}"
        shell: powershell

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15