on:
  workflow_call:

jobs:

  Deploy_Choco:
    name: Deploy WPF Chocolatey
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v2
        name: Download Nightly Signed
        with:
          name: StandaloneSigned
          path: "${{ github.workspace }}\\StandaloneSigned"

      - uses: actions/download-artifact@v3
        name: Download Signing Scripts Artifacts
        with:
          name: SigningScripts
          path: "${{ github.workspace }}/SigningScripts"

      - name: Get Version from File
        run: |
          version = Get-Content "${{ github.workspace }}/SigningScripts/version.txt"
          echo "VERSION=$version" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        name: Download Chocolatey Artifacts
        with:
          name: Chocolatey
          path: "${{ github.workspace }}\\Chocolatey"

      - name: Update Chocolatey Files
        run: |
          .\Build\scripts\hash-files.ps1 -Version "$env:Version"
        shell: powershell

      - name: Push to Chocolatey
        run: |
          # Chocolatey Pack
          & choco.exe pack "${{ github.workspace }}\\Chocolatey\\PresenceLight.nuspec" --version "${{ env.Version }}.0" --OutputDirectory "${{ github.workspace }}\\Chocolatey"

          & choco.exe apikey --key "${{ secrets.CHOCOAPIKEY }}" --source https://push.chocolatey.org/

          $nupkgs = gci "${{ github.workspace }}\\Chocolatey\\PresenceLight.*.nupkg" | Select -ExpandProperty FullName
          foreach ($nupkg in $nupkgs){
            & choco.exe push $nupkg --source https://push.chocolatey.org/
          }
        shell: powershell
