name: Build and Sign

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target of Channel Name to Sign'
        required: true
        default: ''
        type: string

  workflow_call:
    inputs:
      target:
        description: 'Target of Channel Name to Sign'
        required: true
        default: ''
        type: string

jobs:

  run-tests:

    runs-on: windows-latest

    steps:
    - name: Download ${{ inputs.target }} Artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.target }}
        path: ${{ github.workspace }}\ToSign\${{ inputs.target }}

    - uses: actions/download-artifact@v2
      name: Download Signing Scripts Artifacts
      with:
        name: SigningScripts
        path: "${{ github.workspace }}/SigningScripts"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . sign --version 0.9.0-beta.23063.3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code azure-key-vault
        '**/*.{exe,zip}'
        --timestamp-url "http://timestamp.digicert.com"
        --base-directory "${{ github.workspace }}/ToSign"
        --file-list "${{ github.workspace }}/SigningScripts/filelist.txt"
        --publisher-name "Isaac Levin"
        --description "PresenceLight"
        --description-url "https://github.com/isaacrlevin/presencelight"
        --azure-key-vault-managed-identity true
        --azure-key-vault-url "${{ secrets.KEY_VAULT_URL }}"
        --azure-key-vault-certificate "${{ secrets.KEY_VAULT_CERTIFICATE_ID }}"
        --verbosity Trace

    - name: Publish Signed ${{ inputs.target }} Packages
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}\ToSign\${{ inputs.target }}
        name: '${{ inputs.target }}_Signed'