name: Build and Sign

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target of Channel Name to Sign'
        required: true
        default: ''
        type: string

  workflow_call:
    inputs:
      target:
        description: 'Target of Channel Name to Sign'
        required: true
        default: ''
        type: string

jobs:

  Sign_Code:
    name: Sign Code
    permissions:
      id-token: write # Required for requesting the JWT
    runs-on: windows-latest

    steps:
    - name: Download ${{ inputs.target }} Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.target }}
        path: .\ToSign\${{ inputs.target }}

    - uses: actions/download-artifact@v3
      name: Download Signing Scripts Artifacts
      with:
        name: SigningScripts
        path: .\SigningScripts

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x

    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . sign --version 0.9.0-beta.23063.3

    - name: Azure login
      uses: azure/login@v1.5.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code azure-key-vault
        '**/*.{exe,zip,appxbundle,appinstaller}'
        --timestamp-url "http://timestamp.digicert.com"
        --base-directory "${{ github.workspace }}\ToSign"
        --file-list "${{ github.workspace }}\SigningScripts\Signing\filelist.txt"
        --publisher-name "Isaac Levin"
        --description "PresenceLight"
        --description-url "https://github.com/isaacrlevin/presencelight"
        --azure-key-vault-managed-identity true
        --azure-key-vault-url "${{ secrets.KEY_VAULT_URL }}"
        --azure-key-vault-certificate "${{ secrets.KEY_VAULT_CERTIFICATE_ID }}"
        --verbosity Trace

    - name: Publish Signed ${{ inputs.target }} Packages
      uses: actions/upload-artifact@v3
      with:
        path: .\ToSign\${{ inputs.target }}
        name: '${{ inputs.target }}_Signed'

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15