name: Winget
on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Release'
        required: true
        default: '5.0'
        type: string

  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    env:
      WINGETCREATE_TOKEN: ${{ secrets.WINGETCREATE_TOKEN }}
    steps:

      - uses: actions/download-artifact@v3
        if: ${{ github.event_name == 'push' }}
        name: Download Signing Scripts Artifacts
        with:
          name: SigningScripts
          path: ./SigningScripts

      - name: Get Version from Artifact (Push)
        run: |
          version=$(<"${{ github.workspace }}/SigningScripts/version.txt")

      - name: Get Version from Input (Workflow Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          version = "${{ inputs.Version }}"

      - name: Populate Version Environment Variable
        run: |
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create manifest and submit PR
        working-directory: ${{ github.workspace }}/SigningScripts/winget
        run: |
          ./build.ps1 -Version "${{ env.VERSION }}" -Token "${{ secrets.WINGETCREATE_TOKEN }}"
        shell: pwsh

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
